//! Conversation history in SQLite.
//!
//! [`Store`] is a synchronous API over one connection. The app never calls it directly:
//! the runtime sends [`StoreRequest`]s to a [`worker`] thread, which executes them in order
//! and reports results as [`StoreEvent`]s, so the UI loop never waits for the disk.
//!
//! Writes are idempotent upserts ("save this message"), so the app does not need to know
//! whether a row already exists.

use std::{
    path::Path,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use rusqlite::{Connection, OptionalExtension, params};

use crate::state::{Citation, Message, MessageId, MessageStatus, Role};

mod schema;
pub mod worker;

/// Identifier of a stored conversation, generated by the app.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ConversationId(pub String);

/// Conversation-level data written with each message.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConversationRecord {
    pub id: ConversationId,
    /// Set when the conversation is first stored; later values are ignored.
    pub title: String,
    /// Provider id (see `config::Provider`).
    pub provider: String,
    pub model: String,
    /// Document collection searched for each reply (`/rag`).
    pub rag_collection: Option<String>,
    /// Named system prompt (`/persona`).
    pub persona: Option<String>,
}

/// A row of the conversation list.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConversationSummary {
    pub id: ConversationId,
    pub title: String,
    /// Provider id; empty for conversations stored before providers existed.
    pub provider: String,
    pub model: String,
    /// Unix time in seconds.
    pub updated_at: i64,
}

/// A conversation and all its messages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoredConversation {
    pub summary: ConversationSummary,
    pub messages: Vec<Message>,
    /// Id of the first message still in the model's context.
    pub context_start: u64,
    /// Document collection searched for each reply (`/rag`).
    pub rag_collection: Option<String>,
    /// Named system prompt (`/persona`).
    pub persona: Option<String>,
}

/// Work for the storage worker. Requests are short-lived (sent once over a channel), so
/// the size of the message variant does not matter.
#[allow(clippy::large_enum_variant)]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StoreRequest {
    /// Insert or update a message (and create or touch its conversation).
    SaveMessage {
        conversation: ConversationRecord,
        message: Message,
    },
    /// Change the provider and model of a stored conversation.
    SetModel {
        id: ConversationId,
        provider: String,
        model: String,
    },
    /// Move the start of a conversation's context (after `/clear` or `/compact`).
    SetContextStart { id: ConversationId, start: u64 },
    /// Change the named system prompt of a stored conversation (`/persona`).
    SetPersona {
        id: ConversationId,
        persona: Option<String>,
    },
    /// Change the document collection of a stored conversation (`/rag`).
    SetRag {
        id: ConversationId,
        collection: Option<String>,
    },
    /// List conversations, most recent first.
    List,
    /// The user's latest messages, for input history (`Ctrl+↑`).
    InputHistory,
    /// Conversations whose title or messages contain every word of the query.
    Search(String),
    /// Delete a conversation's messages from `from` (a message id) on.
    Truncate { id: ConversationId, from: u64 },
    /// Change a conversation's title.
    Rename { id: ConversationId, title: String },
    /// Delete a conversation and its messages.
    DeleteConversation(ConversationId),
    /// Load one conversation.
    Load(ConversationId),
    /// List document collections (RAG).
    ListCollections,
    /// Delete a document collection's index (`/forget`).
    DeleteCollection(String),
}

/// Results reported by the storage worker.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StoreEvent {
    Listed {
        conversations: Vec<ConversationSummary>,
        /// Time of the listing (Unix seconds), to show relative dates.
        now: i64,
    },
    Loaded(StoredConversation),
    /// Result of [`StoreRequest::Search`]: each conversation with an excerpt of a matching
    /// message (`None` when only the title matches).
    Searched {
        query: String,
        results: Vec<(ConversationSummary, Option<String>)>,
        now: i64,
    },
    /// A conversation was deleted.
    ConversationDeleted(ConversationId),
    /// The user's latest messages, oldest first.
    InputHistory(Vec<String>),
    /// Result of [`StoreRequest::DeleteCollection`]: `found` is `false` if there was none.
    CollectionDeleted {
        name: String,
        found: bool,
    },
    /// Document collections (RAG), listed at `now` (Unix seconds).
    Collections {
        collections: Vec<crate::rag::store::CollectionSummary>,
        now: i64,
    },
    /// User-facing error message.
    Error(String),
}

/// Storage failure.
#[derive(Debug, thiserror::Error)]
pub enum StoreError {
    #[error("{0}")]
    Sqlite(#[from] rusqlite::Error),
    #[error("conversation introuvable")]
    NotFound,
    #[error("donnée invalide : {0}")]
    Corrupt(String),
}

/// Synchronous access to the history database.
#[derive(Debug)]
pub struct Store {
    conn: Connection,
}

impl Store {
    /// Opens (creating if needed) the database file and applies migrations.
    pub fn open(path: &Path) -> Result<Self, StoreError> {
        if let Some(parent) = path.parent() {
            // A missing directory surfaces as an SQLite "unable to open" error below.
            let _ = std::fs::create_dir_all(parent);
        }
        let conn = Connection::open(path)?;
        // Several connections (and chatatui instances) share the file: wait for locks,
        // including the one taken to switch to WAL.
        conn.busy_timeout(Duration::from_secs(5))?;
        enable_wal(&conn)?;
        Self::init(conn)
    }

    /// Opens a private in-memory database (tests).
    pub fn open_in_memory() -> Result<Self, StoreError> {
        Self::init(Connection::open_in_memory()?)
    }

    fn init(mut conn: Connection) -> Result<Self, StoreError> {
        conn.pragma_update(None, "foreign_keys", true)?;
        if schema::version(&conn)? > schema::LATEST_VERSION {
            return Err(StoreError::Corrupt(
                "base créée par une version plus récente de chatatui".into(),
            ));
        }
        schema::migrate(&mut conn)?;
        Ok(Self { conn })
    }

    /// The underlying connection (for the RAG tables).
    pub fn into_connection(self) -> Connection {
        self.conn
    }

    /// Executes a request and turns the outcome into an event (`None` for silent writes).
    pub fn handle(&mut self, request: StoreRequest) -> Option<StoreEvent> {
        let result = match request {
            StoreRequest::SaveMessage {
                conversation,
                message,
            } => self.save_message(&conversation, &message).map(|()| None),
            StoreRequest::SetModel {
                id,
                provider,
                model,
            } => self.set_model(&id, &provider, &model).map(|()| None),
            StoreRequest::SetContextStart { id, start } => {
                self.set_context_start(&id, start).map(|()| None)
            }
            StoreRequest::SetPersona { id, persona } => self
                .conn
                .execute(
                    "UPDATE conversations SET persona = ?2 WHERE id = ?1",
                    params![id.0, persona],
                )
                .map(|_| None)
                .map_err(StoreError::from),
            StoreRequest::SetRag { id, collection } => {
                self.set_rag(&id, collection.as_deref()).map(|()| None)
            }
            StoreRequest::List => self.list().map(|conversations| {
                Some(StoreEvent::Listed {
                    conversations,
                    now: now(),
                })
            }),
            StoreRequest::Load(id) => self.load(&id).map(|c| Some(StoreEvent::Loaded(c))),
            StoreRequest::InputHistory => self
                .input_history(INPUT_HISTORY)
                .map(|h| Some(StoreEvent::InputHistory(h))),
            StoreRequest::Search(query) => self.search(&query).map(|results| {
                Some(StoreEvent::Searched {
                    query,
                    results,
                    now: now(),
                })
            }),
            StoreRequest::Rename { id, title } => self.rename(&id, &title).map(|()| None),
            StoreRequest::Truncate { id, from } => self.truncate(&id, from).map(|()| None),
            StoreRequest::DeleteConversation(id) => self
                .delete(&id)
                .map(|()| Some(StoreEvent::ConversationDeleted(id))),
            StoreRequest::DeleteCollection(name) => {
                crate::rag::store::delete_collection(&mut self.conn, &name)
                    .map(|found| Some(StoreEvent::CollectionDeleted { name, found }))
            }
            StoreRequest::ListCollections => {
                crate::rag::store::list_collections(&self.conn).map(|collections| {
                    Some(StoreEvent::Collections {
                        collections,
                        now: now(),
                    })
                })
            }
        };
        result.unwrap_or_else(|e| Some(StoreEvent::Error(format!("historique : {e}"))))
    }

    /// Inserts or updates a message, creating its conversation if needed.
    pub fn save_message(
        &mut self,
        conversation: &ConversationRecord,
        message: &Message,
    ) -> Result<(), StoreError> {
        self.save_message_at(conversation, message, now())
    }

    /// [`Store::save_message`] with an explicit timestamp (Unix seconds).
    pub fn save_message_at(
        &mut self,
        conversation: &ConversationRecord,
        message: &Message,
        now: i64,
    ) -> Result<(), StoreError> {
        let (status, error) = encode_status(&message.status);
        let tx = self.conn.transaction()?;
        tx.execute(
            "INSERT INTO conversations
                 (id, title, provider, model, rag_collection, persona, created_at, updated_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?7, ?6, ?6)
             ON CONFLICT (id) DO UPDATE SET provider = excluded.provider,
                 model = excluded.model, rag_collection = excluded.rag_collection,
                 persona = excluded.persona,
                 updated_at = excluded.updated_at",
            params![
                conversation.id.0,
                conversation.title,
                conversation.provider,
                conversation.model,
                conversation.rag_collection,
                now,
                conversation.persona
            ],
        )?;
        tx.execute(
            "INSERT INTO messages
                 (conversation_id, seq, role, content, status, error, source, citations,
                  created_at, image_type, image_data)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
             ON CONFLICT (conversation_id, seq) DO UPDATE SET
                 content = excluded.content, status = excluded.status, error = excluded.error,
                 citations = excluded.citations",
            params![
                conversation.id.0,
                i64::try_from(message.id.0).unwrap_or(i64::MAX),
                encode_role(message.role),
                message.content,
                status,
                error,
                message.source,
                encode_citations(&message.citations),
                now,
                message.image.as_ref().map(|i| i.media_type.as_str()),
                message.image.as_ref().map(|i| i.base64.as_str())
            ],
        )?;
        tx.commit()?;
        Ok(())
    }

    /// Moves the context start of a conversation (no-op if it does not exist).
    pub fn set_context_start(&mut self, id: &ConversationId, start: u64) -> Result<(), StoreError> {
        self.conn.execute(
            "UPDATE conversations SET context_start = ?2 WHERE id = ?1",
            params![id.0, i64::try_from(start).unwrap_or(i64::MAX)],
        )?;
        Ok(())
    }

    /// Changes the document collection of a conversation (no-op if it does not exist).
    pub fn set_rag(
        &mut self,
        id: &ConversationId,
        collection: Option<&str>,
    ) -> Result<(), StoreError> {
        self.conn.execute(
            "UPDATE conversations SET rag_collection = ?2 WHERE id = ?1",
            params![id.0, collection],
        )?;
        Ok(())
    }

    /// Changes the provider and model of a conversation (no-op if it does not exist). The
    /// activity date is left untouched so the list order does not change.
    pub fn set_model(
        &mut self,
        id: &ConversationId,
        provider: &str,
        model: &str,
    ) -> Result<(), StoreError> {
        self.conn.execute(
            "UPDATE conversations SET provider = ?2, model = ?3 WHERE id = ?1",
            params![id.0, provider, model],
        )?;
        Ok(())
    }

    /// Conversations matching every word of `query` in their title or messages (accents
    /// and case ignored), most recently updated first.
    pub fn search(
        &self,
        query: &str,
    ) -> Result<Vec<(ConversationSummary, Option<String>)>, StoreError> {
        let Some(fts) = match_all_words(query) else {
            return Ok(self.list()?.into_iter().map(|c| (c, None)).collect());
        };
        let like = format!("%{}%", query.trim().replace(['%', '_'], ""));
        let mut statement = self.conn.prepare(
            "SELECT c.id, c.title, c.provider, c.model, c.updated_at,
                    (SELECT snippet(messages_fts, 0, '', '', '…', 10)
                       FROM messages_fts JOIN messages m ON m.rowid = messages_fts.rowid
                      WHERE messages_fts MATCH ?1 AND m.conversation_id = c.id
                      LIMIT 1)
             FROM conversations c
             WHERE c.title LIKE ?2
                OR c.id IN (SELECT m.conversation_id
                              FROM messages_fts JOIN messages m ON m.rowid = messages_fts.rowid
                             WHERE messages_fts MATCH ?1)
             ORDER BY c.updated_at DESC, c.rowid DESC
             LIMIT 200",
        )?;
        let rows = statement.query_map(params![fts, like], |row| {
            Ok((
                ConversationSummary {
                    id: ConversationId(row.get(0)?),
                    title: row.get(1)?,
                    provider: row.get(2)?,
                    model: row.get(3)?,
                    updated_at: row.get(4)?,
                },
                row.get::<_, Option<String>>(5)?,
            ))
        })?;
        Ok(rows.collect::<Result<_, _>>()?)
    }

    /// Deletes the messages of a conversation from `from` (a message id) on.
    pub fn truncate(&mut self, id: &ConversationId, from: u64) -> Result<(), StoreError> {
        self.conn.execute(
            "DELETE FROM messages WHERE conversation_id = ?1 AND seq >= ?2",
            params![id.0, i64::try_from(from).unwrap_or(i64::MAX)],
        )?;
        Ok(())
    }

    /// Changes a conversation's title (no-op if it does not exist).
    pub fn rename(&mut self, id: &ConversationId, title: &str) -> Result<(), StoreError> {
        self.conn.execute(
            "UPDATE conversations SET title = ?2 WHERE id = ?1",
            params![id.0, title],
        )?;
        Ok(())
    }

    /// The `limit` latest messages the user sent, oldest first, without repeats in a row.
    pub fn input_history(&self, limit: usize) -> Result<Vec<String>, StoreError> {
        let mut statement = self.conn.prepare(
            "SELECT content FROM messages WHERE role = 'user' AND content != ''
             ORDER BY created_at DESC, rowid DESC LIMIT ?1",
        )?;
        let rows = statement.query_map([i64::try_from(limit).unwrap_or(i64::MAX)], |r| {
            r.get::<_, String>(0)
        })?;
        let mut history: Vec<String> = rows.collect::<Result<_, _>>()?;
        history.reverse();
        history.dedup();
        Ok(history)
    }

    /// Deletes a conversation and its messages.
    pub fn delete(&mut self, id: &ConversationId) -> Result<(), StoreError> {
        self.conn
            .execute("DELETE FROM conversations WHERE id = ?1", [&id.0])?;
        Ok(())
    }

    /// All conversations, most recently updated first.
    pub fn list(&self) -> Result<Vec<ConversationSummary>, StoreError> {
        let mut statement = self.conn.prepare(
            "SELECT id, title, provider, model, updated_at FROM conversations
             ORDER BY updated_at DESC, rowid DESC",
        )?;
        let rows = statement.query_map([], |row| {
            Ok(ConversationSummary {
                id: ConversationId(row.get(0)?),
                title: row.get(1)?,
                provider: row.get(2)?,
                model: row.get(3)?,
                updated_at: row.get(4)?,
            })
        })?;
        Ok(rows.collect::<Result<_, _>>()?)
    }

    /// A conversation with its messages in order.
    pub fn load(&self, id: &ConversationId) -> Result<StoredConversation, StoreError> {
        let (summary, context_start, rag_collection, persona) = self
            .conn
            .query_row(
                "SELECT id, title, provider, model, updated_at, context_start, rag_collection,
                        persona
                 FROM conversations WHERE id = ?1",
                [&id.0],
                |row| {
                    Ok((
                        ConversationSummary {
                            id: ConversationId(row.get(0)?),
                            title: row.get(1)?,
                            provider: row.get(2)?,
                            model: row.get(3)?,
                            updated_at: row.get(4)?,
                        },
                        row.get::<_, i64>(5)?,
                        row.get::<_, Option<String>>(6)?,
                        row.get::<_, Option<String>>(7)?,
                    ))
                },
            )
            .optional()?
            .ok_or(StoreError::NotFound)?;

        let mut statement = self.conn.prepare(
            "SELECT seq, role, content, status, error, source, citations, image_type, image_data
             FROM messages
             WHERE conversation_id = ?1 ORDER BY seq",
        )?;
        let rows = statement.query_map([&id.0], |row| {
            Ok((
                row.get::<_, i64>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, String>(3)?,
                row.get::<_, Option<String>>(4)?,
                row.get::<_, Option<String>>(5)?,
                row.get::<_, Option<String>>(6)?,
                row.get::<_, Option<String>>(7)?,
                row.get::<_, Option<String>>(8)?,
            ))
        })?;
        let mut messages = Vec::new();
        for row in rows {
            let (seq, role, content, status, error, source, citations, image_type, image_data) =
                row?;
            messages.push(Message {
                id: MessageId(u64::try_from(seq).map_err(|_| corrupt("seq", &seq))?),
                role: decode_role(&role)?,
                content,
                status: decode_status(&status, error)?,
                source,
                citations: decode_citations(citations.as_deref())?,
                image: match (image_type, image_data) {
                    (Some(media_type), Some(base64)) => {
                        Some(crate::state::Image { media_type, base64 })
                    }
                    _ => None,
                },
            });
        }
        Ok(StoredConversation {
            summary,
            messages,
            context_start: u64::try_from(context_start).unwrap_or(0),
            rag_collection,
            persona,
        })
    }
}

/// FTS5 query requiring every word of `text` (as a prefix). `None` without any word.
fn match_all_words(text: &str) -> Option<String> {
    let words: Vec<String> = text
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| format!("\"{}\"*", w.to_lowercase()))
        .collect();
    (!words.is_empty()).then(|| words.join(" "))
}

/// Switches the file to WAL mode (kept by the file once set). SQLite reports a busy
/// database for this switch without waiting, when another connection is using the file:
/// retry for a moment.
fn enable_wal(conn: &Connection) -> Result<(), StoreError> {
    const ATTEMPTS: u32 = 100;
    let mut attempt = 0;
    loop {
        let result = conn
            .query_row("PRAGMA journal_mode", [], |r| r.get::<_, String>(0))
            .and_then(|mode| {
                if mode.eq_ignore_ascii_case("wal") {
                    Ok(())
                } else {
                    conn.pragma_update(None, "journal_mode", "WAL")
                }
            });
        match result {
            Err(rusqlite::Error::SqliteFailure(e, _))
                if e.code == rusqlite::ErrorCode::DatabaseBusy && attempt < ATTEMPTS =>
            {
                attempt += 1;
                std::thread::sleep(Duration::from_millis(20));
            }
            other => return Ok(other?),
        }
    }
}

/// Messages kept for input history.
const INPUT_HISTORY: usize = 500;

/// Current Unix time in seconds.
fn now() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX))
}

fn corrupt(field: &str, value: &dyn std::fmt::Debug) -> StoreError {
    StoreError::Corrupt(format!("{field} = {value:?}"))
}

fn encode_citations(citations: &[Citation]) -> Option<String> {
    if citations.is_empty() {
        return None;
    }
    serde_json::to_string(citations).ok()
}

fn decode_citations(json: Option<&str>) -> Result<Vec<Citation>, StoreError> {
    match json {
        None | Some("") => Ok(Vec::new()),
        Some(json) => serde_json::from_str(json).map_err(|_| corrupt("citations", &json)),
    }
}

fn encode_role(role: Role) -> &'static str {
    match role {
        Role::System => "system",
        Role::User => "user",
        Role::Assistant => "assistant",
        Role::Attachment => "attachment",
        Role::Summary => "summary",
        Role::Tool => "tool",
    }
}

fn decode_role(role: &str) -> Result<Role, StoreError> {
    match role {
        "system" => Ok(Role::System),
        "user" => Ok(Role::User),
        "assistant" => Ok(Role::Assistant),
        "attachment" => Ok(Role::Attachment),
        "summary" => Ok(Role::Summary),
        "tool" => Ok(Role::Tool),
        other => Err(corrupt("role", &other)),
    }
}

fn encode_status(status: &MessageStatus) -> (&'static str, Option<&str>) {
    match status {
        MessageStatus::Complete => ("complete", None),
        // A reply saved while streaming (should not happen) reads back as interrupted.
        MessageStatus::Streaming | MessageStatus::Cancelled => ("cancelled", None),
        MessageStatus::Failed(error) => ("failed", Some(error)),
    }
}

fn decode_status(status: &str, error: Option<String>) -> Result<MessageStatus, StoreError> {
    match status {
        "complete" => Ok(MessageStatus::Complete),
        "cancelled" => Ok(MessageStatus::Cancelled),
        "failed" => Ok(MessageStatus::Failed(error.unwrap_or_default())),
        other => Err(corrupt("status", &other)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn record(id: &str, title: &str) -> ConversationRecord {
        ConversationRecord {
            id: ConversationId(id.into()),
            title: title.into(),
            provider: "ollama".into(),
            model: "llama3.2".into(),
            rag_collection: None,
            persona: None,
        }
    }

    fn message(seq: u64, role: Role, content: &str, status: MessageStatus) -> Message {
        Message {
            id: MessageId(seq),
            role,
            content: content.into(),
            status,
            source: None,
            citations: Vec::new(),
            image: None,
        }
    }

    fn store() -> Store {
        Store::open_in_memory().expect("in-memory store")
    }

    #[test]
    fn saves_and_loads_a_conversation() {
        let mut store = store();
        let conv = record("c1", "Bonjour");
        let messages = vec![
            message(0, Role::User, "Bonjour", MessageStatus::Complete),
            message(1, Role::Assistant, "Salut **toi**", MessageStatus::Complete),
            message(2, Role::User, "Et ?", MessageStatus::Complete),
            message(3, Role::Assistant, "Il", MessageStatus::Cancelled),
            message(4, Role::User, "Allô", MessageStatus::Complete),
            message(
                5,
                Role::Assistant,
                "",
                MessageStatus::Failed("injoignable".into()),
            ),
        ];
        for m in &messages {
            store.save_message(&conv, m).expect("save");
        }

        let loaded = store.load(&conv.id).expect("load");
        assert_eq!(loaded.summary.title, "Bonjour");
        assert_eq!(loaded.messages, messages);
    }

    #[test]
    fn saving_again_updates_the_message() {
        let mut store = store();
        let conv = record("c1", "t");
        store
            .save_message(
                &conv,
                &message(0, Role::Assistant, "a", MessageStatus::Cancelled),
            )
            .expect("save");
        store
            .save_message(
                &conv,
                &message(0, Role::Assistant, "ab", MessageStatus::Complete),
            )
            .expect("save");
        let loaded = store.load(&conv.id).expect("load");
        assert_eq!(loaded.messages.len(), 1);
        assert_eq!(loaded.messages[0].content, "ab");
        assert_eq!(loaded.messages[0].status, MessageStatus::Complete);
    }

    #[test]
    fn title_is_kept_but_provider_and_model_follow_the_last_save() {
        let mut store = store();
        let m = message(0, Role::User, "x", MessageStatus::Complete);
        store
            .save_message(&record("c1", "Premier"), &m)
            .expect("save");
        let mut later = record("c1", "Autre titre");
        later.provider = "claude".into();
        later.model = "claude-test".into();
        store.save_message(&later, &m).expect("save");
        let summary = &store.list().expect("list")[0];
        assert_eq!(summary.title, "Premier");
        assert_eq!(summary.provider, "claude");
        assert_eq!(summary.model, "claude-test");
    }

    #[test]
    fn set_model_changes_only_provider_and_model() {
        let mut store = store();
        let m = message(0, Role::User, "x", MessageStatus::Complete);
        store
            .save_message_at(&record("c1", "t"), &m, 100)
            .expect("save");
        store
            .set_model(&ConversationId("c1".into()), "openai", "gpt-test")
            .expect("set model");
        let summary = &store.list().expect("list")[0];
        assert_eq!(summary.provider, "openai");
        assert_eq!(summary.model, "gpt-test");
        assert_eq!(summary.updated_at, 100);
        store
            .set_model(&ConversationId("unknown".into()), "x", "y")
            .expect("unknown id is a no-op");
    }

    #[test]
    fn list_is_most_recent_first() {
        let mut store = store();
        let m = message(0, Role::User, "x", MessageStatus::Complete);
        for (id, time) in [("a", 100), ("b", 200), ("c", 300)] {
            store
                .save_message_at(&record(id, id), &m, time)
                .expect("save");
        }
        // A new message in "a" makes it the most recent.
        let reply = message(1, Role::Assistant, "y", MessageStatus::Complete);
        store
            .save_message_at(&record("a", "a"), &reply, 400)
            .expect("save");
        store
            .save_message_at(&record("d", "d"), &m, 400)
            .expect("save");

        let ids: Vec<String> = store
            .list()
            .expect("list")
            .into_iter()
            .map(|s| s.id.0)
            .collect();
        assert_eq!(ids, ["d", "a", "c", "b"], "ties: newest conversation first");
    }

    #[test]
    fn loading_an_unknown_conversation_fails() {
        let store = store();
        assert!(matches!(
            store.load(&ConversationId("nope".into())),
            Err(StoreError::NotFound)
        ));
    }

    #[test]
    fn handle_reports_errors_as_events() {
        let mut store = store();
        let event = store.handle(StoreRequest::Load(ConversationId("nope".into())));
        assert_eq!(
            event,
            Some(StoreEvent::Error(
                "historique : conversation introuvable".into()
            ))
        );
        let saved = store.handle(StoreRequest::SaveMessage {
            conversation: record("c", "t"),
            message: message(0, Role::User, "x", MessageStatus::Complete),
        });
        assert_eq!(saved, None, "successful writes are silent");
    }

    #[test]
    fn newer_schema_is_refused() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = dir.path().join("history.db");
        {
            let conn = Connection::open(&path).expect("open");
            conn.pragma_update(None, "user_version", 99)
                .expect("pragma");
        }
        assert!(matches!(Store::open(&path), Err(StoreError::Corrupt(_))));
    }

    #[test]
    fn data_survives_reopening_the_file() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = dir.path().join("sub").join("history.db");
        {
            let mut store = Store::open(&path).expect("open");
            store
                .save_message(
                    &record("c1", "t"),
                    &message(0, Role::User, "persisté", MessageStatus::Complete),
                )
                .expect("save");
        }
        let store = Store::open(&path).expect("reopen");
        let loaded = store.load(&ConversationId("c1".into())).expect("load");
        assert_eq!(loaded.messages[0].content, "persisté");
    }

    #[test]
    fn attachments_summaries_and_context_start_round_trip() {
        let mut store = store();
        let conv = record("c1", "t");
        let attachment = Message {
            source: Some("~/notes.md".into()),
            ..message(
                0,
                Role::Attachment,
                "texte du fichier",
                MessageStatus::Complete,
            )
        };
        let summary = message(1, Role::Summary, "- résumé", MessageStatus::Complete);
        store.save_message(&conv, &attachment).expect("save");
        store.save_message(&conv, &summary).expect("save");
        store.set_context_start(&conv.id, 1).expect("context start");

        let loaded = store.load(&conv.id).expect("load");
        assert_eq!(loaded.messages, vec![attachment, summary]);
        assert_eq!(loaded.context_start, 1);
    }

    #[test]
    fn citations_and_collection_round_trip() {
        let mut store = store();
        let mut conv = record("c1", "t");
        conv.rag_collection = Some("cours".into());
        let mut reply = message(1, Role::Assistant, "Voir [1].", MessageStatus::Complete);
        reply.citations = vec![Citation {
            number: 1,
            path: "plan.docx".into(),
            location: "§ Séance 1".into(),
        }];
        store.save_message(&conv, &reply).expect("save");
        let loaded = store.load(&conv.id).expect("load");
        assert_eq!(loaded.messages, vec![reply]);
        assert_eq!(loaded.rag_collection.as_deref(), Some("cours"));

        store.set_rag(&conv.id, None).expect("set");
        assert_eq!(store.load(&conv.id).expect("load").rag_collection, None);
    }

    #[test]
    fn search_finds_words_in_messages_and_titles() {
        let mut store = store();
        let save = |store: &mut Store, conv: &str, title: &str, seq: u64, text: &str, at: i64| {
            store
                .save_message_at(
                    &record(conv, title),
                    &message(seq, Role::User, text, MessageStatus::Complete),
                    at,
                )
                .expect("save");
        };
        save(
            &mut store,
            "a",
            "Emprunts",
            0,
            "Comment fonctionne le système d'emprunt ?",
            1,
        );
        save(
            &mut store,
            "b",
            "Traits",
            0,
            "Qu'est-ce qu'un trait générique ?",
            2,
        );
        save(&mut store, "c", "Vacances", 0, "Idées de départ", 3);
        let ids = |results: Vec<(ConversationSummary, Option<String>)>| -> Vec<String> {
            results.into_iter().map(|(c, _)| c.id.0).collect()
        };

        assert_eq!(
            ids(store.search("generique").expect("search")),
            vec!["b"],
            "accents"
        );
        assert_eq!(
            ids(store.search("EMPRUNT systeme").expect("search")),
            vec!["a"]
        );
        assert!(
            store.search("emprunt trait").expect("search").is_empty(),
            "all words"
        );
        let hits = store.search("vacances").expect("search");
        assert_eq!(hits[0].1, None, "title only: no excerpt");
        let hits = store.search("fonctionne").expect("search");
        assert!(
            hits[0]
                .1
                .as_deref()
                .is_some_and(|s| s.contains("fonctionne"))
        );
        assert_eq!(
            store.search("  ").expect("all").len(),
            3,
            "empty query lists all"
        );

        // Edited messages are searchable under their new text only.
        save(&mut store, "c", "Vacances", 0, "Planning des examens", 4);
        assert!(store.search("depart").expect("search").is_empty());
        assert_eq!(ids(store.search("examens").expect("search")), vec!["c"]);

        store
            .rename(&ConversationId("c".into()), "Examens de juin")
            .expect("rename");
        assert_eq!(
            store
                .load(&ConversationId("c".into()))
                .expect("load")
                .summary
                .title,
            "Examens de juin"
        );
        store.delete(&ConversationId("c".into())).expect("delete");
        assert!(store.search("examens").expect("search").is_empty());
        assert_eq!(store.list().expect("list").len(), 2);
    }

    #[test]
    fn images_round_trip_outside_the_text() {
        let mut store = store();
        let conv = record("c1", "t");
        let image = Message {
            source: Some("schéma.png".into()),
            image: Some(crate::state::Image {
                media_type: "image/png".into(),
                base64: "iVBORw==".into(),
            }),
            ..message(0, Role::Attachment, "", MessageStatus::Complete)
        };
        store.save_message(&conv, &image).expect("save");
        assert_eq!(store.load(&conv.id).expect("load").messages, vec![image]);
        assert!(
            store.search("iVBORw").expect("search").is_empty(),
            "not indexed"
        );
    }

    #[test]
    fn input_history_lists_the_latest_questions() {
        let mut store = store();
        let save = |store: &mut Store, conv: &str, seq: u64, role: Role, text: &str, at: i64| {
            store
                .save_message_at(
                    &record(conv, "t"),
                    &message(seq, role, text, MessageStatus::Complete),
                    at,
                )
                .expect("save");
        };
        save(&mut store, "a", 0, Role::User, "un", 1);
        save(&mut store, "a", 1, Role::Assistant, "réponse", 2);
        save(&mut store, "b", 0, Role::User, "deux", 3);
        save(&mut store, "b", 1, Role::User, "deux", 4);
        save(&mut store, "b", 2, Role::User, "trois", 5);
        assert_eq!(
            store.input_history(10).expect("history"),
            vec!["un", "deux", "trois"]
        );
        assert_eq!(
            store.input_history(2).expect("history"),
            vec!["deux", "trois"]
        );
    }
}
